spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false #osiv
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 3